# Generated by Django 3.0.3 on 2020-06-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='delegacion',
            field=models.CharField(default='Del', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='entre_calle_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='entre_calle_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='interior',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='referencias',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
