# Generated by Django 3.0.3 on 2020-04-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_delete_extendeduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='a@gmail.com', help_text='Required', max_length=200)),
                ('telefono', models.CharField(max_length=200, null=True)),
                ('calle', models.CharField(max_length=200)),
                ('interior', models.CharField(max_length=100, null=True)),
                ('exterior', models.CharField(max_length=100, null=True)),
                ('colonia', models.CharField(max_length=100, null=True)),
                ('codigoPostal', models.CharField(max_length=100, null=True)),
                ('entreCalle', models.CharField(max_length=100, null=True)),
                ('ycalle', models.CharField(max_length=100, null=True)),
                ('referencias', models.CharField(max_length=200, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='users/media/users/{instance.id}_{instance.name}_{filename}')),
            ],
        ),
    ]
