# Generated by Django 3.0.3 on 2020-04-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200422_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='a@example.com', max_length=200),
        ),
    ]
