# Generated by Django 3.0.3 on 2020-04-27 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='foto',
        ),
    ]
