# Generated by Django 3.0.3 on 2020-05-05 05:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0009_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='users',
        ),
        migrations.AddField(
            model_name='customer',
            name='users',
            field=models.ManyToManyField(null=True, related_name='customers', to=settings.AUTH_USER_MODEL),
        ),
    ]
