# Generated by Django 3.0.3 on 2020-05-05 05:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_auto_20200505_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='users',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='users',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
