# Generated by Django 3.0.3 on 2020-06-05 19:41

from django.db import migrations, models
import restaurante.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=restaurante.models.element_image_directory_path),
        ),
        migrations.AlterField(
            model_name='element',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=restaurante.models.element_image_directory_path),
        ),
    ]
