# Generated by Django 3.0.3 on 2020-04-16 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='categoria',
        ),
        migrations.DeleteModel(
            name='platillo',
        ),
    ]
