# Generated by Django 3.0.3 on 2020-04-09 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0003_auto_20200409_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date_created',
        ),
    ]
