# Generated by Django 3.0.3 on 2020-06-10 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0003_order_orderelement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderelement',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_elems', to='restaurante.Order'),
        ),
    ]
