# Generated by Django 3.0.3 on 2020-06-11 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0004_auto_20200610_0022'),
        ('restaurante', '0004_auto_20200610_0320'),
    ]

    operations = [
    ]
