# Generated by Django 3.0.3 on 2020-04-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0005_auto_20200409_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='a@gmail.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
