# Generated by Django 3.0.3 on 2020-04-10 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0006_auto_20200410_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='street',
            new_name='calle',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='btStreet1',
            new_name='codigoPostal',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='btStreet2',
            new_name='entreCalle',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='extNumber',
            new_name='exterior',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='photo',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='interNum',
            new_name='interior',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='referencias',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='referennces',
            new_name='telefono',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='postalCode',
            new_name='ycalle',
        ),
    ]
