# Generated by Django 3.0.3 on 2020-04-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0007_auto_20200410_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='restaurante/media/users/{instance.id}_{instance.name}_{filename}'),
        ),
    ]
