# Generated by Django 3.0.3 on 2020-04-15 01:30

from django.db import migrations, models
import restaurante.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0009_auto_20200413_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platillo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=restaurante.models.image_directory_path),
        ),
    ]
