# Generated by Django 3.0.3 on 2020-04-18 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0010_auto_20200414_2030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
