# Generated by Django 3.0.3 on 2020-05-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0011_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='platillo',
            name='categoria',
            field=models.ManyToManyField(null=True, related_name='customers', to='restaurante.categoria'),
        ),
    ]
