# Generated by Django 3.0.3 on 2020-05-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0012_platillo_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
