# Generated by Django 3.0.3 on 2020-05-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0014_auto_20200505_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platillo',
            name='categoria',
            field=models.ManyToManyField(null=True, to='restaurante.Categoria'),
        ),
        migrations.AlterField(
            model_name='platillo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
