# Generated by Django 3.0.3 on 2020-05-06 02:14

from django.db import migrations, models
import restaurante.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0015_auto_20200505_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platillo',
            name='categoria',
            field=models.ManyToManyField(null=True, to='restaurante.Categoria'),
        ),
        migrations.AlterField(
            model_name='platillo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=restaurante.models.image_directory_path),
        ),
    ]
