# Generated by Django 3.0.3 on 2020-05-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0016_auto_20200505_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platillo',
            name='categoria',
            field=models.ManyToManyField(null=True, to='restaurante.Categoria'),
        ),
    ]
