# Generated by Django 3.0.3 on 2020-05-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0017_auto_20200505_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platillo',
            name='categoria',
            field=models.ManyToManyField(null=True, to='restaurante.Categoria'),
        ),
    ]
